class AppStrings {
  static const String appName = "AgroMitra";
  static const String taglineEn = "Know the Market. Sell with Confidence.";
  static const String taglineHi = "बाज़ार को जानें। आत्मविश्वास से बेचें।";
  static const String taglineMr = "बाजारपेठ समजून घ्या. आत्मविश्वासाने विका.";

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'AgroMitra',
      'tagline': 'Know the Market. Sell with Confidence.',
      'choose_language': 'Choose Your Language',
      'continue_btn': 'Continue',
      'continue_farmer': 'Continue as Farmer',
      'continue_buyer': 'Continue as Buyer',
      'farmer_card_title': 'Farmer / Kisan',
      'farmer_card_desc': 'Check latest Mandi benchmarks and list crops at fair prices.',
      'buyer_card_title': 'Produce Buyer / Vyapari',
      'buyer_card_desc': 'Discover fresh farm produce directly from verified farmers without middlemen.',
      'admin_login_link': 'Admin Login',
      'kisan_login': 'Farmer Login',
      'kisan_signup': 'Farmer Signup',
      'buyer_login': 'Buyer Login',
      'buyer_signup': 'Buyer Signup',
      'admin_login': 'Admin Portal',
      'phone_number': 'Phone Number',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'full_name': 'Full Name',
      'village': 'Village / Village Panchayat',
      'taluka': 'Taluka / Tehsil',
      'district': 'District',
      'login_btn': 'Login',
      'create_account': 'Create Account',
      'already_account': 'Already have an account? Login',
      'new_kisan': 'New to AgroMitra? Create Farmer Account',
      'new_buyer': 'New Buyer? Create Account',
      'forgot_password': 'Forgot Password?',
      'forgot_password_demo': 'Demo Notice: For the hackathon prototype, self-service password recovery is handled via Admin console. Use default demo credentials or contact Admin.',
      
      // Navigation
      'nav_home': 'Home',
      'nav_prices': 'Mandi Prices',
      'nav_sell': 'Sell Produce',
      'nav_schemes': 'Govt Schemes',
      'nav_profile': 'Profile',
      'nav_search': 'Search Produce',
      
      // Farmer Home
      'greeting': 'Good Morning,',
      'today_mandi_highlight': "Today's Mandi Highlight",
      'modal_price': 'Modal Price',
      'min_price': 'Min Price',
      'max_price': 'Max Price',
      'quick_actions': 'Quick Actions',
      'recent_listings': 'Your Recent Listings',
      'view_all': 'View All',
      'weather_title': 'Weather Forecast (Demo)',
      'news_title': 'Agricultural Updates & Mandi News',
      
      // Mandi Prices Screen
      'search_commodity_hint': 'Search commodity (e.g. Tomato, Onion)...',
      'filter_all': 'All',
      'latest_mandi_price_disclaimer': 'Data Source: Latest available APMC / Agmarknet benchmark data. Not tick-by-tick trading.',
      'price_trend': '7-Day Price Trend (Benchmark)',
      
      // Sell Produce Flow
      'sell_step1': '1. Details',
      'sell_step2': '2. Photos',
      'sell_step3': '3. AI Grade',
      'sell_step4': '4. Pricing',
      'select_commodity': 'Select Commodity',
      'quantity': 'Quantity Available',
      'unit': 'Unit (Quintal / Kg)',
      'crop_desc': 'Produce Description & Harvest Date',
      'upload_photos_title': 'Upload Produce Photos (Up to 3)',
      'take_camera': 'Take Photo',
      'choose_gallery': 'Choose from Gallery',
      'ai_grade_title': 'AI-Assisted Visual Quality Suggestion',
      'ai_disclaimer': 'Advisory only. You can adjust the grade below.',
      'confidence': 'Confidence',
      'suggested_grade': 'Suggested Grade',
      'grade_a': 'Grade A (Premium)',
      'grade_b': 'Grade B (Standard)',
      'grade_c': 'Grade C (Fair)',
      'pricing_formula_title': 'Transparent Price Formula',
      'mandi_benchmark': 'Mandi Benchmark Modal Price',
      'quality_factor': 'Quality Multiplier',
      'suggested_asking_price': 'Suggested Price',
      'final_asking_price': 'Your Final Asking Price (₹/kg)',
      'publish_listing': 'Publish Listing',
      'listing_success_title': 'Listing Published Successfully! 🌾',
      'listing_success_desc': 'Your produce is now visible to active buyers in your district and state.',
      
      // My Listings
      'my_listings_title': 'My Produce Records',
      'status_active': 'ACTIVE',
      'status_sold': 'SOLD',
      'mark_sold': 'Mark as Sold',
      'edit_listing': 'Edit Listing',
      
      // Government Schemes
      'schemes_title': 'Government Schemes 🇮🇳',
      'schemes_subtitle': 'Central & State agricultural subsidies, insurance, and solar schemes for farmers.',
      'category_all': 'All Schemes',
      'category_subsidy': 'Subsidy',
      'category_insurance': 'Insurance',
      'category_loan': 'Credit & Loan',
      'category_women': 'Women Farmers',
      'category_organic': 'Organic Farming',
      'scheme_eligibility': 'Eligibility Criteria',
      'scheme_benefits': 'Direct Benefits',
      'scheme_documents': 'Required Documents',
      'scheme_process': 'How to Apply',
      'apply_official_website': 'Open Official Portal',
      'redirecting_notice': 'Redirecting to official Government portal.',
      
      // Buyer Flow
      'buyer_hero_title': 'Find Fresh Farm Produce',
      'buyer_hero_subtitle': 'Directly from local verified farmers in Maharashtra',
      'search_placeholder': 'Search by crop or district...',
      'featured_commodities': 'Featured Commodities',
      'recommended_districts': 'Nearby Agricultural Hubs',
      'trending_listings': 'Trending Fresh Harvests',
      'contact_farmer': 'Contact Farmer',
      'compare_mandi_badge': 'Mandi Benchmark Comparison',
      'farmer_price': 'Farmer Asking Price',
      'mandi_diff': 'vs Mandi Modal',
      'contact_confirmation': 'Do you want to dial and connect with the farmer directly?',
      'call_now': 'Call Farmer',
      'cancel': 'Cancel',
      
      // Profile
      'profile_title': 'Farmer Profile',
      'buyer_profile_title': 'Buyer Profile',
      'allow_calls': 'Allow Buyers to Contact Me',
      'edit_profile': 'Edit Profile Details',
      'logout': 'Log Out',
      
      // Admin
      'admin_title': 'AgroMitra Admin Control',
      'admin_users': 'Active Users',
      'admin_listings': 'Marketplace Listings',
      'admin_prices': 'Mandi Benchmarks',
      'admin_seller_status': 'Demo Seller Verification Status',
      'verified': 'VERIFIED',
      'unverified': 'UNVERIFIED',
    },
    'hi': {
      'app_name': 'एग्रोमित्र',
      'tagline': 'बाज़ार को जानें। आत्मविश्वास से बेचें।',
      'choose_language': 'अपनी भाषा चुनें',
      'continue_btn': 'आगे बढ़ें',
      'continue_farmer': 'किसान के रूप में जारी रखें',
      'continue_buyer': 'खरीदार के रूप में जारी रखें',
      'farmer_card_title': 'किसान भाई / Kisan',
      'farmer_card_desc': 'नवीनतम मंडी भाव देखें और अपनी फसल सही दाम पर बेचें।',
      'buyer_card_title': 'उपज खरीदार / Vyapari',
      'buyer_card_desc': 'सीधे सत्यापित किसानों से बिना किसी बिचौलिए के ताजी फसल खरीदें।',
      'admin_login_link': 'एडमिन लॉगिन',
      'kisan_login': 'किसान लॉगिन',
      'kisan_signup': 'किसान पंजीकरण',
      'buyer_login': 'खरीदार लॉगिन',
      'buyer_signup': 'खरीदार पंजीकरण',
      'admin_login': 'एडमिन पोर्टल',
      'phone_number': 'मोबाइल नंबर',
      'password': 'पासवर्ड',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'full_name': 'पूरा नाम',
      'village': 'गाँव / ग्राम पंचायत',
      'taluka': 'तालुका / तहसील',
      'district': 'ज़िला',
      'login_btn': 'लॉगिन करें',
      'create_account': 'खाता बनाएं',
      'already_account': 'पहले से खाता है? लॉगिन करें',
      'new_kisan': 'नए किसान? एग्रोमित्र खाता बनाएं',
      'new_buyer': 'नए खरीदार? खाता बनाएं',
      'forgot_password': 'पासवर्ड भूल गए?',
      'forgot_password_demo': 'डेमो सूचना: हैकथॉन प्रोटोटाइप के लिए पासवर्ड रिकवरी एडमिन द्वारा की जा सकती है।',
      
      'nav_home': 'होम',
      'nav_prices': 'मंडी भाव',
      'nav_sell': 'फसल बेचें',
      'nav_schemes': 'सरकारी योजनाएं',
      'nav_profile': 'प्रोफ़ाइल',
      'nav_search': 'फसल खोजें',
      
      'greeting': 'नमस्ते,',
      'today_mandi_highlight': 'आज का प्रमुख मंडी भाव',
      'modal_price': 'मॉडल भाव',
      'min_price': 'न्यूनतम भाव',
      'max_price': 'अधिकतम भाव',
      'quick_actions': 'त्वरित सेवाएं',
      'recent_listings': 'आपकी हालिया फसलें',
      'view_all': 'सभी देखें',
      'weather_title': 'मौसम का अनुमान (डेमो)',
      'news_title': 'कृषि समाचार एवं मंडी अपडेट',
      
      'search_commodity_hint': 'फसल खोजें (उदा. टमाटर, प्याज)...',
      'filter_all': 'सभी',
      'latest_mandi_price_disclaimer': 'स्रोत: नवीनतम उपलब्ध एपीएमसी / एगमार्कनेट मानक दरें।',
      'price_trend': '7 दिनों का भाव रुझान',
      
      'sell_step1': '1. विवरण',
      'sell_step2': '2. फोटो',
      'sell_step3': '3. AI ग्रेड',
      'sell_step4': '4. मूल्य',
      'select_commodity': 'फसल चुनें',
      'quantity': 'उपलब्ध मात्रा',
      'unit': 'इकाई (क्विंटल / किग्रा)',
      'crop_desc': 'फसल विवरण और कटाई की तारीख',
      'upload_photos_title': 'फसल की फोटो अपलोड करें (अधिकतम 3)',
      'take_camera': 'कैमरा से फोटो लें',
      'choose_gallery': 'गैलरी से चुनें',
      'ai_grade_title': 'AI-सहायक गुणवत्ता सुझाव',
      'ai_disclaimer': 'सलाहकारी मात्र। आप नीचे ग्रेड बदल सकते हैं।',
      'confidence': 'सटीकता',
      'suggested_grade': 'सुझाया गया ग्रेड',
      'grade_a': 'ग्रेड A (उत्कृष्ट)',
      'grade_b': 'ग्रेड B (सामान्य)',
      'grade_c': 'ग्रेड C (औसत)',
      'pricing_formula_title': 'पारदर्शी मूल्य निर्धारण सूत्र',
      'mandi_benchmark': 'मंडी मॉडल भाव',
      'quality_factor': 'गुणवत्ता गुणांक',
      'suggested_asking_price': 'सुझाया गया मूल्य',
      'final_asking_price': 'आपका अंतिम विक्रय मूल्य (₹/किग्रा)',
      'publish_listing': 'फसल सूची प्रकाशित करें',
      'listing_success_title': 'फसल सफलतापूर्वक सूचीबद्ध हुई! 🌾',
      'listing_success_desc': 'आपकी उपज अब नजदीकी और राज्य स्तरीय खरीदारों को दिखाई दे रही है।',
      
      'my_listings_title': 'मेरी फसलें और रिकॉर्ड',
      'status_active': 'सक्रिय',
      'status_sold': 'बिक चुका',
      'mark_sold': 'बिका हुआ चिह्नित करें',
      'edit_listing': 'बदलाव करें',
      
      'schemes_title': 'सरकारी योजनाएं 🇮🇳',
      'schemes_subtitle': 'किसानों के लिए केंद्रीय व राज्य स्तरीय सब्सिडी, फसल बीमा और ऋण योजनाएं।',
      'category_all': 'सभी योजनाएं',
      'category_subsidy': 'सब्सिडी',
      'category_insurance': 'फसल बीमा',
      'category_loan': 'ऋण व केसीसी',
      'category_women': 'महिला किसान',
      'category_organic': 'जैविक खेती',
      'scheme_eligibility': 'पात्रता मानदंड',
      'scheme_benefits': 'प्रमुख लाभ',
      'scheme_documents': 'आवश्यक दस्तावेज',
      'scheme_process': 'आवेदन प्रक्रिया',
      'apply_official_website': 'आधिकारिक पोर्टल खोलें',
      'redirecting_notice': 'आधिकारिक सरकारी पोर्टल पर पुनर्निर्देशित किया जा रहा है।',
      
      'buyer_hero_title': 'ताजी उपज खोजें',
      'buyer_hero_subtitle': 'महाराष्ट्र के सत्यापित किसानों से सीधे खरीदें',
      'search_placeholder': 'फसल या ज़िला खोजें...',
      'featured_commodities': 'प्रमुख फसलें',
      'recommended_districts': 'नजदीकी कृषि क्षेत्र',
      'trending_listings': 'ताजा उपलब्ध फसलें',
      'contact_farmer': 'किसान से संपर्क करें',
      'compare_mandi_badge': 'मंडी भाव तुलना',
      'farmer_price': 'किसान का भाव',
      'mandi_diff': 'मंडी भाव अंतर',
      'contact_confirmation': 'क्या आप सीधे किसान को फोन कॉल करना चाहते हैं?',
      'call_now': 'कॉल करें',
      'cancel': 'रद्द करें',
      
      'profile_title': 'किसान प्रोफ़ाइल',
      'buyer_profile_title': 'खरीदार प्रोफ़ाइल',
      'allow_calls': 'खरीदारों को संपर्क करने की अनुमति दें',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'logout': 'लॉग आउट',
      
      'admin_title': 'एग्रोमित्र एडमिन डैशबोर्ड',
      'admin_users': 'सक्रिय उपयोगकर्ता',
      'admin_listings': 'उपज सूचियाँ',
      'admin_prices': 'मंडी भाव प्रबंधन',
      'admin_seller_status': 'सत्यापन स्थिति',
      'verified': 'सत्यापित',
      'unverified': 'असत्यापित',
    },
    'mr': {
      'app_name': 'ऍग्रोमित्र',
      'tagline': 'बाजारपेठ समजून घ्या. आत्मविश्वासाने विका.',
      'choose_language': 'आपली भाषा निवडा',
      'continue_btn': 'पुढे जा',
      'continue_farmer': 'शेतकरी म्हणून सुरू ठेवा',
      'continue_buyer': 'खरेदीदार म्हणून सुरू ठेवा',
      'farmer_card_title': 'शेतकरी बांधव / Kisan',
      'farmer_card_desc': 'मंडीचे ताजे भाव तपासा आणि योग्य भावात शेतमाल विका.',
      'buyer_card_title': 'शेतमाल खरेदीदार / Vyapari',
      'buyer_card_desc': 'थेट स्थानिक शेतकऱ्यांकडून मध्यस्थांशिवाय दर्जेदार शेतीमाल खरेदी करा.',
      'admin_login_link': 'प्रशासक (Admin) लॉगिन',
      'kisan_login': 'शेतकरी लॉगिन',
      'kisan_signup': 'शेतकरी नोंदणी',
      'buyer_login': 'खरेदीदार लॉगिन',
      'buyer_signup': 'खरेदीदार नोंदणी',
      'admin_login': 'Admin पोर्टल',
      'phone_number': 'मोबाईल नंबर',
      'password': 'पासवर्ड',
      'confirm_password': 'पासवर्ड पुष्टी करा',
      'full_name': 'पूर्ण नाव',
      'village': 'गाव / ग्रामपंचायत',
      'taluka': 'तालुका',
      'district': 'जिल्हा',
      'login_btn': 'लॉगिन करा',
      'create_account': 'खाते तयार करा',
      'already_account': 'आधीच खाते आहे? लॉगिन करा',
      'new_kisan': 'नवीन शेतकरी? खाते तयार करा',
      'new_buyer': 'नवीन खरेदीदार? खाते तयार करा',
      'forgot_password': 'पासवर्ड विसरलात?',
      'forgot_password_demo': 'डेमो सूचना: हॅकाथॉनसाठी पासवर्ड रीसेट ॲडमिन कडून उपलब्ध आहे.',
      
      'nav_home': 'मुख्यपृष्ठ',
      'nav_prices': 'बाजारभाव',
      'nav_sell': 'माल विका',
      'nav_schemes': 'सरकारी योजना',
      'nav_profile': 'प्रोफाइल',
      'nav_search': 'माल शोधा',
      
      'greeting': 'शुभ सकाळ,',
      'today_mandi_highlight': 'आजचे प्रमुख बाजारभाव',
      'modal_price': 'सरासरी भाव',
      'min_price': 'किमान भाव',
      'max_price': 'कमाल भाव',
      'quick_actions': 'जलद सेवा',
      'recent_listings': 'आपला उपलब्ध शेतमाल',
      'view_all': 'सर्व पहा',
      'weather_title': 'हवामान अंदाज (डेमो)',
      'news_title': 'कृषी घडामोडी व बाजार वृत्त',
      
      'search_commodity_hint': 'शेतमाल शोधा (उदा. टोमॅटो, कांदा)...',
      'filter_all': 'सर्व',
      'latest_mandi_price_disclaimer': 'माहिती स्त्रोत: अधिकृत APMC / ॲगमार्कनेट ताजे बाजारभाव.',
      'price_trend': 'मागील ७ दिवसांचा भाव कल',
      
      'sell_step1': '१. तपशील',
      'sell_step2': '२. फोटो',
      'sell_step3': '३. AI दर्जा',
      'sell_step4': '४. किंमत',
      'select_commodity': 'शेतमाल निवडा',
      'quantity': 'उपलब्ध प्रमाण',
      'unit': 'एकक (क्विंटल / किलो)',
      'crop_desc': 'मालाचे वर्णन व काढणी तारीख',
      'upload_photos_title': 'मालाचे फोटो अपलोड करा (जास्तीत जास्त ३)',
      'take_camera': 'कॅमेऱ्याने फोटो काढा',
      'choose_gallery': 'गॅलरीतून निवडा',
      'ai_grade_title': 'AI गुणवत्ता दर्जा सल्ला',
      'ai_disclaimer': 'केवळ मार्गदर्शनासाठी. आपण खाली ग्रेड बदलू शकता.',
      'confidence': 'अचूकता',
      'suggested_grade': 'सुचवलेला ग्रेड',
      'grade_a': 'ग्रेड A (उत्कृष्ट प्रत)',
      'grade_b': 'ग्रेड B (मध्यम प्रत)',
      'grade_c': 'ग्रेड C (साधारण प्रत)',
      'pricing_formula_title': 'पारदर्शक दर निर्धारण सूत्र',
      'mandi_benchmark': 'मंडी सरासरी (Modal) भाव',
      'quality_factor': 'गुणवत्ता गुणक',
      'suggested_asking_price': 'सुचवलेला विक्री दर',
      'final_asking_price': 'आपला अंतिम विक्री दर (₹/किलो)',
      'publish_listing': 'शेतमाल लिस्ट करा',
      'listing_success_title': 'शेतमाल यशस्वीपणे लिस्ट झाला! 🌾',
      'listing_success_desc': 'आपला शेतीमाल आता राज्यातील सर्व खरेदीदारांना दिसत आहे.',
      
      'my_listings_title': 'माझा शेतमाल व नोंदी',
      'status_active': 'उपलब्ध',
      'status_sold': 'विक्री झालेला',
      'mark_sold': 'विक्री झाले म्हणून नोंदवा',
      'edit_listing': 'बदल करा',
      
      'schemes_title': 'शासकीय कृषी योजना 🇮🇳',
      'schemes_subtitle': 'शेतकऱ्यांसाठी केंद्र व राज्य शासनाच्या अनुदान, पीक विमा आणि सौर कृषी योजना.',
      'category_all': 'सर्व योजना',
      'category_subsidy': 'अनुदान योजना',
      'category_insurance': 'पीक विमा',
      'category_loan': 'कर्ज व KCC',
      'category_women': 'महिला शेतकरी',
      'category_organic': 'सेंद्रिय शेती',
      'scheme_eligibility': 'पात्रता अटी',
      'scheme_benefits': 'योजनेचे लाभ',
      'scheme_documents': 'आवश्यक कागदपत्रे',
      'scheme_process': 'अर्ज करण्याची पद्धत',
      'apply_official_website': 'अधिकृत संकेतस्थळ उघडा',
      'redirecting_notice': 'शासकीय अधिकृत पोर्टलवर पाठवले जात आहे.',
      
      'buyer_hero_title': 'ताजा शेतमाल शोधा',
      'buyer_hero_subtitle': 'महाराष्ट्रातील स्थानिक शेतकऱ्यांकडून थेट खरेदी करा',
      'search_placeholder': 'शेतमाल किंवा जिल्हा शोधा...',
      'featured_commodities': 'प्रमुख पिके',
      'recommended_districts': 'जवळचे कृषी जिल्हे',
      'trending_listings': 'नवीनतम शेतमाल',
      'contact_farmer': 'शेतकऱ्याशी संपर्क साधा',
      'compare_mandi_badge': 'मंडी भाव तुलना',
      'farmer_price': 'शेतकऱ्याचा दर',
      'mandi_diff': 'मंडी भाव फरक',
      'contact_confirmation': 'आपण शेतकऱ्याला थेट फोन करू इच्छिता का?',
      'call_now': 'कॉल करा',
      'cancel': 'रद्द करा',
      
      'profile_title': 'शेतकरी प्रोफाईल',
      'buyer_profile_title': 'खरेदीदार प्रोफाईल',
      'allow_calls': 'खरेदीदारांना थेट कॉल करण्याची परवानगी द्या',
      'edit_profile': 'माहिती दुरुस्त करा',
      'logout': 'बाहेर पडा (Logout)',
      
      'admin_title': 'ॲग्रोमित्र ॲडमिन पॅनल',
      'admin_users': 'वापरकर्ते',
      'admin_listings': 'शेतमाल यादी',
      'admin_prices': 'बाजारभाव व्यवस्थापन',
      'admin_seller_status': 'सत्यापन स्थिती',
      'verified': 'सत्यापित',
      'unverified': 'असत्यापित',
    }
  };

  static String get(String key, {String lang = 'en'}) {
    final langMap = _localizedValues[lang] ?? _localizedValues['en']!;
    return langMap[key] ?? _localizedValues['en']![key] ?? key;
  }
}
